
[balancing]
	#How much should a fluid point transfer?
	#Range: 1 ~ 1000000
	fluidPointTransfer = 50
	#How much should an essence point transfer? (Applies to all essence point types)
	#Range: 1 ~ 1000000
	essencePointTransfer = 50
	#How much should an item point transfer?
	#Range: 1 ~ 64
	itemPointTransfer = 4
	#How much should an essence battery hold? (Applies to all essence point types)
	#Range: 1 ~ 1000000
	essenceBatteryMax = 10000

